---
language: ruby
sudo: false

rvm:
  - 2.1.5

# don't load beaker stuff - this does not work with Ruby 1.8
# and we don't use it on Travis either way
bundler_args: --without system_tests

before_install:
  - 'gem install bundler'

script:
  - bundle install
  - bundle update
  - bundle exec rake all

env:
  - PUPPET_VERSION="4.2"
